# Generated by Django 4.1.3 on 2022-11-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tickets', models.IntegerField()),
                ('confirm', models.BooleanField(default=False)),
            ],
        ),
    ]
