# Generated by Django 4.1.3 on 2022-11-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmation',
            name='message',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
