# Generated by Django 4.1.3 on 2022-11-20 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_confirmation_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmation',
            options={'verbose_name': 'Confirmation', 'verbose_name_plural': 'Confirmations'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'Family', 'verbose_name_plural': 'Families'},
        ),
    ]
